### PR TITLE
fix: browser does not open when there are token files

### LINKED ISSUE #2398: Failed to launch the browser process! undefined
## Environment

- **Venom version(s):** [5.0.11]
- **Browser:** [chrome 115.0.5790.98]
- **OS:** [ubuntu 20.04]
- **Node version:** [node 18]

## Steps to Reproduce

1. try to create a new session

## Log Output

```
Path Google-Chrome:  /usr/bin/google-chrome-stable
Error: Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/math/dev/DeliveryHub/back/node_modules/.pnpm/@puppeteer+browsers@1.4.5_typescript@4.9.5/node_modules/@puppeteer/browsers/src/launch.ts:399:11)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

## Your Code

```
private async start() {
    this.client = await create({
      session: 'session',
      headless: 'new',
    });
  }
```

### PR DESCRIPTION
**Pull request by BLRocha**
Fixes #2398.

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:BLRocha/venom#fix_tokens_error_issue_2377`

### CODE REVIEW

File: src/controllers/browser.ts [hunk 1]
```diff
@@ -434,3 +435,15 @@ function isChromeInstalled(executablePath: string): boolean {
     return false;
   }
 }
+
+function removeStoredSingletonLock(puppeteerOptions): boolean {
+  const platform = os.platform();
+  const { userDataDir } = puppeteerOptions;
+  try {
+    if (platform === 'win32') return false;
+    fs.unlinkSync(`${userDataDir}/SingletonLock`);
```
Comment (jonalan7) [inline src/controllers/browser.ts:602]: This path is not for all users, that is, it is not global!

File: src/controllers/browser.ts [hunk 2]
```diff
@@ -328,6 +328,7 @@ export async function initBrowser(
       return await puppeteer.connect({ browserWSEndpoint: options.browserWS });
     } else {
       console.log('aqui');
+      removeStoredSingletonLock(options.puppeteerOptions);
```
Comment (jonalan7) [inline src/controllers/browser.ts:489]: This function of deleting the token should not be placed here because how would we be able to recover the token later? It's important to keep the token available for use. Perhaps it would be more appropriate to implement a deactivation or revocation function for the token if needed, instead of permanently deleting it.

**Comment by niron1** [comment]
I had this problem too, then I learned that by removing content of 'tokens' directory the issue is resolved. however, I wonder if I am the only one who needs to scan the QR Code each and every time I restart the server? I just keep getting
`Error: Failed to launch the browser process! undefined
✓ Platform: linux
✓ Chrome Version: built
TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/app/venom/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at ChildProcess.emit (node:events:524:35)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)`

 it might be related that I run from a docker

File: src/controllers/browser.ts (hunk 2 above)
Comment (BLRocha) [reply src/controllers/browser.ts:489]: the function does not remove the existing tokens, it only removes the `SingletonLock` symbolic link that causes the lock on OSX and Linux platforms.

Comment (niron1) [reply src/controllers/browser.ts:489]: @BLRocha  this is great ! thank you !! now I learn that I don't need to erase the 'tokens' folder, just the singletonLock, and I don't need to re-scan the QR ! 🤗🤗🤗

@jonalan7 I believe the following would be a good compromise:

in controllers/initializer.ts ,
```
    if (typeof browser === 'boolean') {
      spinnies.fail(`browser-${session}`, {
        text: `Error no open browser....`
      });
      removeStoredSingletonLock(options.puppeteerOptions);
      statusFind && statusFind('noOpenBrowser', session);
      return reject(`Error no open browser....`);
    }
```

File: src/controllers/browser.ts (hunk 1 above)
Comment (BLRocha) [reply src/controllers/browser.ts:602]: I will check.

File: src/controllers/browser.ts (hunk 2 above)
Comment (jonalan7) [reply src/controllers/browser.ts:489]: I'm thinking that it might be an issue with the new Headless mode they added to Chrome. You can find information about it at this link: https://developer.chrome.com/articles/new-headless/

I believe we should make "new" an option, not the default. I suggest using "true" or "false" for now, until we can investigate further

File: src/controllers/browser.ts (hunk 1 above)
Comment (jonalan7) [reply src/controllers/browser.ts:602]: If I delete the SingletonLock folder, will the login work normally? In other words, will it be necessary to scan the QR code again?

**Comment by jonalan7** [comment]
#2377
